fix

diff --git a/.github/workflows/build_create.yml b/.github/workflows/build_create.yml
--- a/.github/workflows/build_create.yml
+++ b/.github/workflows/build_create.yml
@@ -107,4 +107,9 @@ jobs:
     runs-on: ubuntu-latest
     needs: [provision-slices]
     steps:
-      - run: echo The build process completed successfully.
+      - run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "Testing failed"
+            exit 1
+          fi
+          echo "Testing passed"
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -47,5 +47,10 @@ jobs:
     runs-on: ubuntu-latest
     needs: [testing]
     steps:
-      - run: echo The build process completed successfully.
+      - run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "Testing failed"
+            exit 1
+          fi
+          echo "Testing passed"
 
